import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Header from "@/components/Header";
import ViewCanvas from "@/components/ViewCanvas";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alpino = localFont({
  src: [
    {
      path: "./fonts/Alpino-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "./fonts/Alpino-Variable.woff",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-alpino",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fizzi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${alpino.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden bg-lime-300">
        <Header />
        <main>
          {children}
          <ViewCanvas />
        </main>
        <script
          async
          defer
          src="https://static.cdn.prismic.io/prismic.js?new=true&repo=fizzi-srd"
        ></script>
      </body>
    </html>
  );
}
